services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    environment:
      node.name: es01
      cluster.name: es-docker-cluster
      discovery.type: single-node
      xpack.security.enabled: false  # 보안 기능 비활성화
      TZ: Asia/Seoul
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.1
    container_name: kibana
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200  # SSL/TLS 비활성화
      TZ: Asia/Seoul
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch

networks:
  default:
    name: today-net
    external: true